USE [ExaminationSystemDB]
GO

CREATE SCHEMA Parson

--ACCOUNT TABLE
CREATE TABLE Parson.ACCOUNT
(
	ID INT IDENTITY,
	USERNAME VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL
	CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_ACCOUNT_NAME UNIQUE (USERNAME),
	CONSTRAINT CK_ACCOUNT_PASSWORD CHECK(LEN(PASSWORD) >= 8 AND LEN(PASSWORD)<=20),
)ON ExamSystem_FG1;

GO

-- INSTRUCTOR TABLE

CREATE TABLE Parson.INSTRUCTOR 
(
	SSN CHAR(14),
	[NAME] VARCHAR(50) NOT NULL,
	SALARY int NOT NULL,
	GENDER CHAR(1) NOT NULL DEFAULT 'M',
	BIRTH_DATE DATE NOT NULL,
	AGE AS DATEDIFF(YEAR,BIRTH_DATE,GETDATE()),
	PHONE CHAR(11) NOT NULL,
	[ADDRESS] VARCHAR(20) NOT NULL,
	ACCOUNT_ID INT,
	BRANCH_ID INT ,
	Is_Manager Bit CONSTRAINT DF_INSTRUCTOR_Is_Manager DEFault 0 NOT NULL,
	CONSTRAINT PK_INSTRUCTOR_SSN PRIMARY KEY (SSN),
	CONSTRAINT CK_INSTRUCTOR_SSN CHECK (LEN(SSN) = 14),
	CONSTRAINT CK_INSTRUCTOR_GENDER CHECK(UPPER(GENDER) IN ('M','F')),
	CONSTRAINT FK_INSTRUCTOR_ACCOUNTID 

	FOREIGN KEY (ACCOUNT_ID) REFERENCES Parson.ACCOUNT(ID) ON UPDATE CASCADE ,
	CONSTRAINT FK_INSTRUCTOR_BRANCHID 

	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID) ON UPDATE CASCADE ON DELETE SET NULL,
)ON ExamSystem_FG1; 

GO

CREATE RULE PHONE_ROLE 
AS @PHONE LIKE '01[0125][0-9]%%%%%%%%'

GO

SP_BINDRULE PHONE_ROLE,'INSTRUCTOR.PHONE'

GO

CREATE TABLE Parson.STUDENT 
(
	SSN CHAR(14),
	[FULL_NAME] VARCHAR(50) NOT NULL,
	GENDER CHAR(1) NOT NULL DEFAULT 'M',
	BIRTH_DATE DATE NOT NULL,
	PHONE CHAR(11) NOT NULL,
	AGE AS DATEDIFF(YEAR,BIRTH_DATE,GETDATE()),
	[ADDRESS] VARCHAR(20) NOT NULL,
	ACCOUNT_ID INT,
	CONSTRAINT PK_STUDENT_SSN PRIMARY KEY (SSN),
	CONSTRAINT CK_STUDENT_SSN CHECK (LEN(SSN) = 14),
	CONSTRAINT CK_STUDENT_GENDER CHECK(UPPER(GENDER) IN ('M','F')),
	
	CONSTRAINT FK_STUDENT_ACCOUNTID 
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Parson.ACCOUNT(ID) ON UPDATE CASCADE 
)ON ExamSystem_FG2; 

GO

SP_BINDRULE PHONE_ROLE,'STUDENT.PHONE'