CREATE TABLE QUESTION(
	[ID] INT IDENTITY(1,1),
	[QUESTION] VARCHAR(150) NOT NULL,
	[CREATED_AT] DATE CONSTRAINT DF_QUESTION_CREATED_AT DEFAULT GETDATE(),
	[TYPE] CHAR(13) NOT NULL,
	CONSTRAINT PK_QUESTION_ID PRIMARY KEY ([ID]),
	CONSTRAINT CK_QUESTION_TYPE CHECK(UPPER([TYPE]) IN ('TEXT','CHOOSE','TRUE OR FALSE')),
)

CREATE TABLE EXAM (
	[ID] INT IDENTITY(1,1),
	[YEAR] INT CONSTRAINT DF_EXAM_YEAR DEFAULT YEAR(GETDATE()),
	[START_TIME] DATETIME NOT NULL,
	[END_TIME] DATETIME NOT NULL,
	[TOTAL_TIME] AS DATEDIFF(MINUTE,[END_TIME],[START_TIME]) PERSISTED,
	[ALLOWNECE] NVARCHAR(150),
	[INSTRUCTOR_SSN] CHAR(14) NOT NULL,
	CONSTRAINT PK_EXAM_ID PRIMARY KEY ([ID]),
	CONSTRAINT FK_EXAM_INSTRUCTOR_SSN FOREIGN KEY ([INSTRUCTOR_SSN]) REFERENCES INSTRUCTOR(SSN)
)



CREATE TABLE EXAM_QUESTION (
	[ID] INT IDENTITY(1,1),
	[EXAM_ID] INT NOT NULL,
	[QUESTION_ID] INT NOT NULL,
	[DEGREE] INT NOT NULL,
	CONSTRAINT PK_EXAM_QUESTION_ID PRIMARY KEY ([ID]),
	CONSTRAINT FK_EXAM_QUESTION_EXAM_ID FOREIGN KEY ([EXAM_ID]) REFERENCES EXAM(ID),
	CONSTRAINT FK_EXAM_QUESTION_QUESTION_ID FOREIGN KEY ([QUESTION_ID]) REFERENCES QUESTION(ID),
	CONSTRAINT UQ_EXAM_QUESTION_EXAM_ID_AND_QUESTION_ID UNIQUE([EXAM_ID],[QUESTION_ID]),
	CONSTRAINT CK_EXAM_QUESTION_DEGREE CHECK([DEGREE] > 0)
)


CREATE TABLE STUDENT_EXAM (
	[ID] INT IDENTITY(1,1),
	[STUDENT_SSN] CHAR(14) NOT NULL,
	[EXAM_ID] INT NOT NULL,
	[RESULT] FLOAT NOT NULL,
	[TYPE] CHAR(1) NOT NULL,
	CONSTRAINT PK_STUDENT_EXAM_ID PRIMARY KEY ([ID]),
	CONSTRAINT FK_STUDENT_EXAM_STUDENT_SSN FOREIGN KEY ([STUDENT_SSN]) REFERENCES STUDENT(SSN),
	CONSTRAINT FK_STUDENT_EXAM_EXAM_ID FOREIGN KEY ([EXAM_ID]) REFERENCES EXAM(ID),
	CONSTRAINT UQ_STUDENT_EXAM_EXAM_ID_AND_QUESTION_ID UNIQUE([EXAM_ID],[STUDENT_SSN]),
	CONSTRAINT CK_STUDENT_EXAM_TYPE CHECK(UPPER([TYPE]) IN ('C','E')),
	CONSTRAINT CK_STUDENT_EXAM_RESULT CHECK([RESULT] >= 0)
)

