--BRANCH TABLE
CREATE TABLE BRANCH
(
    ID INT IDENTITY,
    [NAME] VARCHAR(50) NOT NULL,
    [LOCATION] VARCHAR(20) NOT NULL,
    MANAGER_ID CHAR(14),
    CONSTRAINT PK_BRANCH_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_BRANCH_NAME UNIQUE (NAME),
) ON ExamSystem_FG1;

ALTER TABLE BRANCH 
ADD CONSTRAINT FK_BRANCH_MANAGERID FOREIGN KEY(MANAGER_ID)
REFERENCES INSTRUCTOR(SSN) 

ALTER TABLE BRANCH DROP CONSTRAINT FK_BRANCH_MANAGERID

ALTER TABLE BRANCH
ALTER COLUMN MANAGER_ID CHAR(14) NOT NULL

ALTER TABLE BRANCH
ADD CONSTRAINT UQ_BRANCH_MANAGERID UNIQUE (MANAGER_ID)


--DEPARTMENT TABLE
CREATE TABLE DEPARTMENT
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--TRACK TABLE
CREATE TABLE TRACK
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TRACK_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_TRACK_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--INTAKE TABLE
CREATE TABLE INTAKE
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	CONSTRAINT PK_INTAKE_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_INTAKE_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--BRANCH_DEPARTMENT_INTAKE_TRACK THAT MADE FORM TERNARY RELATION BETWEEN THE 4 TABLES
CREATE TABLE BRANCH_DEPARTMENT_INTAKE_TRACK
(
	ID INT IDENTITY,
	BRNACH_ID INT NOT NULL,
	DEPARTMENT_ID INT NOT NULL,
	INTAKE_ID INT NOT NULL,
	TRACK_ID INT NOT NULL,
	CONSTRAINT PK_BDIT_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_BDIT_BRNACHID_DEPARTMENTID_INTAKEID_TRACKID 
			   UNIQUE (BRNACH_ID,DEPARTMENT_ID,INTAKE_ID,TRACK_ID),
	CONSTRAINT FK_BDIT_BRANCHID FOREIGN KEY (BRNACH_ID) REFERENCES BRANCH(ID),
	CONSTRAINT FK_BDIT_DEPARTMENTID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
	CONSTRAINT FK_BDIT_INTAKEID FOREIGN KEY (INTAKE_ID) REFERENCES INTAKE(ID),
	CONSTRAINT FK_BDIT_TRACKID FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID),
)ON ExamSystem_FG1;

--SYNONYM TO MAKE ALIAS NAME FOR BRANCH_DEPARTMENT_INTAKE_TRACK TABLE
CREATE SYNONYM BDIT FOR BRANCH_DEPARTMENT_INTAKE_TRACK;


--COURSE TABLE
CREATE TABLE COURSE
(
	CODE CHAR(5),
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	MIN_DEGREE INT NOT NULL,
	MAX_DEGREE INT NOT NULL,
	CONSTRAINT PK_COURSE_CODE PRIMARY KEY(CODE),
	CONSTRAINT UQ_COURSE_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--ACCOUNT TABLE
CREATE TABLE ACCOUNT
(
	ID INT IDENTITY,
	USERNAME VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL
	CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_ACCOUNT_NAME UNIQUE (USERNAME),
	CONSTRAINT CK_ACCOUNT_PASSWORD CHECK(LEN(PASSWORD) >= 8 AND LEN(PASSWORD)<=20),
)ON ExamSystem_FG1;

CREATE TABLE INSTRUCTOR 
(
	SSN CHAR(14),
	[NAME] VARCHAR(50) NOT NULL,
	SALARY int NOT NULL,
	GENDER CHAR(1) NOT NULL DEFAULT 'M',
	BIRTH_DATE DATE NOT NULL,
	AGE AS DATEDIFF(YEAR,BIRTH_DATE,GETDATE()),
	PHONE CHAR(11) NOT NULL,
	[ADDRESS] VARCHAR(20) NOT NULL,
	ACCOUNT_ID INT,
	BRANCH_ID INT ,
	CONSTRAINT PK_INSTRUCTOR_SSN PRIMARY KEY (SSN),
	CONSTRAINT CK_INSTRUCTOR_SSN CHECK (LEN(SSN) = 14),
	CONSTRAINT CK_INSTRUCTOR_GENDER CHECK(UPPER(GENDER) IN ('M','F')),
	CONSTRAINT FK_INSTRUCTOR_ACCOUNTID 

	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON UPDATE CASCADE ,
	CONSTRAINT FK_INSTRUCTOR_BRANCHID 

	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID) ON UPDATE CASCADE ON DELETE SET NULL,
)ON ExamSystem_FG1; 

CREATE RULE PHONE_ROLE 
AS @PHONE LIKE '01[0125][0-9]%%%%%%%%'

SP_BINDRULE PHONE_ROLE,'INSTRUCTOR.PHONE'


SELECT B.NAME,I.NAME AS MANAGER
FROM BRANCH AS B JOIN INSTRUCTOR AS I
ON B.MANAGER_ID=I.SSN