USE[ExaminationSystemDB]

GO

CREATE SCHEMA Organization

--BRANCH TABLE
CREATE TABLE Organization.BRANCH
(
    ID INT IDENTITY,
    [NAME] VARCHAR(50) NOT NULL,
    [LOCATION] VARCHAR(20) NOT NULL,
    MANAGER_ID CHAR(14),
    CONSTRAINT PK_BRANCH_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_BRANCH_NAME UNIQUE (NAME),
) ON ExamSystem_FG1;


--DEPARTMENT TABLE
CREATE TABLE Organization.DEPARTMENT
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--TRACK TABLE
CREATE TABLE Organization.TRACK
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TRACK_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_TRACK_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;

--INTAKE TABLE
CREATE TABLE Organization.INTAKE
(
	ID INT IDENTITY,
	[NAME] VARCHAR(50) NOT NULL,
	CONSTRAINT PK_INTAKE_ID PRIMARY KEY(ID),
	CONSTRAINT UQ_INTAKE_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;


--COURSE TABLE
CREATE TABLE Organization.COURSE
(
	CODE CHAR(5),
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(100) NOT NULL,
	MIN_DEGREE INT NOT NULL,
	MAX_DEGREE INT NOT NULL,
	CONSTRAINT PK_COURSE_CODE PRIMARY KEY(CODE),
	CONSTRAINT UQ_COURSE_NAME UNIQUE (NAME),
)ON ExamSystem_FG1;





SELECT B.NAME,I.NAME AS MANAGER
FROM BRANCH AS B JOIN INSTRUCTOR AS I
ON B.MANAGER_ID=I.SSN