-- VIEW TO SHOW ALL DATA ABOUT BRANCHES AND DEPARTMENTS
SELECT * FROM Organization.V_Branch_Department;

-- VIEW TO SHOW ALL DATA ABOUT TRACKS IN BRANCHES AND DEPARTMENTS
SELECT * FROM Organization.V_Branch_Department_Track;

-- VIEW TO SHOW ALL DATA ABOUT INTAKES ON EACH TRACK IN EACH DEPARTMENT IN EACH BRANCH
SELECT B_Name, D_Name 
FROM Organization.V_Branch_Department_Track_Intake;

-- VIEW TO SHOW ALL DATA ABOUT STUDENTS ON EACH INTAKE, TRACK, AND DEPARTMENT IN EACH BRANCH
SELECT * 
FROM Organization.V_Branche_Department_Track_Intake_Students;

-- VIEW TO SHOW ALL DATA ABOUT INSTRUCTORS, COURSES, AND THEIR ASSOCIATION WITH INTAKES, TRACKS, DEPARTMENTS, AND BRANCHES
SELECT * 
FROM Organization.V_Branch_Department_Track_Intake_Instructor_Course;

-- VIEW TO SHOW ALL DATA ABOUT STUDENTS AND THEIR EXAMS
SELECT * 
FROM Organization.V_Student_Eaxm;

-- VIEW TO SHOW ALL DATA ABOUT QUESTIONS IN EXAMS
SELECT * 
FROM Exam.V_Exam_Questions;

-- VIEW TO SHOW ALL DATA ABOUT MULTIPLE-CHOICE QUESTION CHOICES IN EXAMS
SELECT * 
FROM Exam.V_Exam_Questions_Choices;

-- VIEW TO SHOW ALL DATA ABOUT TRUE/FALSE QUESTIONS IN EXAMS
SELECT * 
FROM Exam.V_Exam_Questions_T_F;

-- VIEW TO SHOW ALL DATA ABOUT TEXT QUESTIONS IN EXAMS
SELECT * 
FROM Exam.V_Exam_Questions_TEXT;

-- VIEW TO SHOW ALL DATA ABOUT STUDENTS' ANSWERS IN EXAMS
SELECT * 
FROM Answer.V_Student_Answer;

-- VIEW TO SHOW ALL DATA ABOUT TRUE/FALSE ANSWERS SUBMITTED BY STUDENTS IN EXAMS
SELECT * 
FROM Answer.V_Student_Answer_T_F;

-- VIEW TO SHOW ALL DATA ABOUT MULTIPLE-CHOICE ANSWERS SUBMITTED BY STUDENTS IN EXAMS
SELECT * 
FROM Answer.V_Student_Answer_MCQ;

-- VIEW TO SHOW ALL DATA ABOUT TEXT ANSWERS SUBMITTED BY STUDENTS IN EXAMS
SELECT * 
FROM Answer.V_Student_Answer_Text;
